### ISSUE TITLE
Update containers

### ISSUE THREAD

**Issue by jclemons7** [sherifabdlnaby/elastdocker#14]
I'm sure I'm just missing it in the documentation, but how would I update the containers to a newer ELK stack version after the initial installation and configuration without losing data?

I used the project to build a 7.7.0 stack and it worked perfectly, but if I do this.. how would I subsequently upgrade to 7.8.0 for instance?  I can always change the build number in the script, but if I run it again then I lose my data.

Thanks in advance.

**Comment by sherifabdlnaby** [comment]
1. You won't lose your data, Data are in Docker Volumes and it needs to be explicitly deleted, they are not inside the containers and won't be deleted with it. 
2. New MINOR versions are compatible with the data, so just upgrading the `ELK_VERSION` in `.env` should be enough.

**Comment by jclemons7** [comment]
After that, do I just do the make setup; make elk thing again ?

**Comment by sherifabdlnaby** [comment]
Only `make elk` will do, you won't be needing `make setup` unless you want to change saved credentials or want to refresh/change certificates used.
