### ISSUE TITLE
ElastAlert plugin

### ISSUE THREAD

**Issue by Bouzeghoub** [sherifabdlnaby/elastdocker#16]
Hello,
ElastAlert plugin for kibana is compatible with 7.7.0 ?
Best regards

**Comment by sherifabdlnaby** [comment]
@Bouzeghoub No, ElastAlert plugin is no longer supported for newer Kibana versions. There are forks that support up to 7.8.0 though.

**Comment by Bouzeghoub** [comment]
Thank you so much Bro.

**Comment by sherifabdlnaby** [comment]
All the included tools are supported for ELK 7.8.0.
I can’t list all other Kibana tools/plugins as they are so many.
What are you looking for exactly?

**Comment by Bouzeghoub** [comment]
Thank  you Bro,
Please, I want complete SIEM platform.

**Comment by sherifabdlnaby** [comment]
It's a good start having Elastic Stack up and running, you can then start the Trial version and experiment.
For more information check https://www.elastic.co/siem

**Comment by Bouzeghoub** [comment]
I apologize, I got tired of you.
I want to automate deploy this platform with Docker after with K8S.
![image](https://user-images.githubusercontent.com/16193005/86580018-09390780-bf76-11ea-909c-073c2736b6ba.png)

**Comment by sherifabdlnaby** [comment]
Then you have the first thing Up which is Elastic Stack, also ElastAlert is included with Elastdocker. You need to spin up all these other tools incrementally until you achieve what you want. I can't really help much to be honest.
