### ISSUE TITLE
Docker swarm support

### ISSUE THREAD

**Issue by pravnkr** [sherifabdlnaby/elastdocker#17]
Ask a question...
How the elastdocker can be used with docker swarm..

**Comment by sherifabdlnaby** [comment]
It should be easy to convert the setup to Docker Swarm instead of compose, I will work on that when I have time.

**Comment by sherifabdlnaby** [comment]
Docker Swarm support in the next release, however, I do not recommend it.
Elastdocker is not designed for workloads that need more than a single host, if I need more than one host then I recommend Kubernetes or a SaaS offering. 

Docker Swarm does not support setting `ulimts`, to use elastdocker setup you need to disable `bootstrap.memory_lock` in `docker-compose.yml` and find a way to disable swapping and increase `nofile` in swarm.
