### ISSUE TITLE
Getting errors on kibana and logstash

### ISSUE THREAD

**Issue by doludizgin** [sherifabdlnaby/elastdocker#18]
i just runned the script, didnt make any changes.

Elastic cluster gets created but kibana and logstash are giving errors:

{"type":"log","@timestamp":"2020-08-04T15:37:44Z","tags":["warning","elasticsearch","admin"],"pid":8,"message":"Unable to revive connection: http://elasticsearch:9200/"}

If i do a:

curl -XGET -u elastic:changeme 'localhost:9200/_cluster/health?pretty it gives an output of the cluster.

So that part is runnig fine, looks like kibana cant communicate somehow with the cluster.

Can you help ?

**Comment by doludizgin** [comment]
If i test from the kibana docker console to the elasticsearch:9200 i get a no route to host, but i can ping the elasticsearch on the internal ip addr.

**Comment by sherifabdlnaby** [comment]
Weird. Please inspect the network created and see if all containers shares the same network.

**Comment by doludizgin** [comment]
i found it, its an Centos 8 problem with docker dns:

https://github.com/docker/for-linux/issues/957

(1) just use masquerade will make this work

firewall-cmd --zone=public  --add-masquerade --permanent
firewall-cmd --reload
from comment in <https://linuxconfig.org/how-to-install-docker-in-rhel-8 >

(2)set docker0 to trusted

firewall-cmd --zone=trusted --add-interface=docker0 --permanent
firewall-cmd --reload

**Comment by sherifabdlnaby** [comment]
Thank you for posting the solution you found, I will add a note to the README for CentOS 8 users.
