### ISSUE TITLE
SSL Certificates 

### ISSUE THREAD

**Issue by notwedtm** [sherifabdlnaby/elastdocker#2]
It appears that SSL certificates that are generated during `make setup` never get injected into any containers. Is this a missing step?

**Comment by sherifabdlnaby** [comment]
They're mounted as a secret, refer to the `docker-compose.yml` secrets part.

Docker-Compose won't start if they were not generated, and Elasticsearch won't start without having the SSL Certificates mounted if you succeeded in starting Elasticsearch.

so just do `make setup` followed by `make elk` or `make all` and you should be good to go.
