### ISSUE TITLE
Unable to change default user/password

### ISSUE THREAD

**Issue by ricardo-lobo** [sherifabdlnaby/elastdocker#20]
I have tried to change the default user/password in the .env

Ran the make setup but didn't fix anything

With the default configuration everything works fine.

**Comment by sherifabdlnaby** [comment]
Please make sure you restart the stack.
I can change password using `make setup` and `.env` using the latest version of elastdocker.

Make sure filesystem ain't cached (Sometimes in MacOS this happen)

**Comment by sherifabdlnaby** [comment]
I’m closing this issue _for now_ because of inactivity and my inability to reproduced the behavior you mention.
@ricardo-lobo we can always reopen it though! :)

**Comment by ricardo-lobo** [comment]
> I’m closing this issue _for now_ because of inactivity and my inability to reproduced the behavior you mention.
> @ricardo-lobo we can always reopen it though! :)

Sorry for not giving any feedback regarding this issue. Actually I also cannot reproduce this error again. It was probably misconfiguration from my part! Thanks for the repo!
