### ISSUE TITLE
Production readiness

### ISSUE THREAD

**Issue by hashwin** [sherifabdlnaby/elastdocker#22]
Hi @sherifabdlnaby 

Firstly, nice idea on this project, I feel very strongly about this that setting up an elastic cluster should not be such an effort, especially when deploying projects on multiple client locations. I should just be able to, after setting my domain name and node configuration, run a single command on my server, and I should have, out of the box, Elasticsearch, Kibana, Elastic APM, Beats and Logstash completely secured and ready to go.

However, there seem to be some gaps in deploying a working version of this.
- While this project is labeled to be for a production cluster, all the rest of the documentation seems to only be talking about localhost. Ideally there should be some documentation on how to get this running on a server exposed to the web.
- In your screenshots, your chrome shows "Not Secure", presumably because of the self signed certificate. A more thorough approach would be to add let's encrypt to the repo and allow auto-issuing certificates automatically when the cluster is spun up. Tools like Caprover to this to great effect. Any particular reason http security is not enabled by default?

**Comment by sherifabdlnaby** [comment]
Hey @hashwin

I am glad you found this project useful. As for:

>While this project is labeled to be for a production cluster, all the rest of the documentation seems to only be talking about localhost. Ideally there should be some documentation on how to get this running on a server exposed to the web.

Elastdocker is ideally used for a small workload single node cluster on a single docker host managed manually (No Swarm or K8s, etc), exposing this host to the web (or your other internal networks) varies depending on your service provider (EC2, Azure, etc), so the documentation focuses on setting up the docker host itself and it is up to the operator to exposes it to the web. Nevertheless, If you'd like to create documentation for -say a EC2 host- then that would be a welcomed addition. 

> In your screenshots, your chrome shows "Not Secure", presumably because of the self-signed certificate. A more thorough approach would be to add let's encrypt to the repo and allow auto-issuing certificates automatically when the cluster is spun up. Tools like Caprover to this to great effect. 

Adding Let's Encrypt to the setup will be a very good addition, I will add it to the project TODOs and if you'd like to contribute that would be very welcomed 🙏 

> Any particular reason http security is not enabled by default?

Enabling SSL on Elasticsearch's HTTP layer will require all clients that connect to Elasticsearch to configure SSL connection for HTTP, this includes all the currently configured parts of the stack (e.g Logstash, Kibana, Curator, etc) plus any library/binding that connects to Elasticsearch from your application code, it complicates the setup so much when one of the goals of the project is to spin up ELK hassle-free and be able to experiment with it or develop using it quickly.

Notice that typically Elasticsearch is not exposed to the web, so although we should assume a zero-trust network, it is not critical to have Elasticsearch HTTP layer not secured when we're starting our ELK cluster.

However, new features of Elastic Stack such as alerts require TLS for HTTP layer, so adding it in a different branch can be an option too.
