### ISSUE TITLE
TLS isn't setup

### ISSUE THREAD

**Issue by SelfhostedPro** [sherifabdlnaby/elastdocker#24]
**Describe the bug**
TLS doesn't get setup when following the setup.

**To Reproduce**
1. On a fresh node, clone the repo.
2. Run `make setup`
3. Run `make elk`

**Expected behavior**
TLS security is setup so native alerting works.

**Screenshots**
![image](https://user-images.githubusercontent.com/66331933/93899110-d5ce6500-fca8-11ea-805e-1a6001f2d458.png)

Only changes I made was setting the elk version to 7.9.0

**Comment by sherifabdlnaby** [comment]
This is not a bug, in the README It is mentioned that the TLS is set up for Transport Layer only and not HTTP Layer.

> ### Enable SSL on HTTP
> 
> By default, only Transport Layer has SSL Enabled, to enable SSL on HTTP layer, add the following lines to `elasticsearch.yml`
> ```yaml
> ## - http
> xpack.security.http.ssl.enabled: true
> xpack.security.http.ssl.key: certs/elasticsearch.key
> xpack.security.http.ssl.certificate: certs/elasticsearch.crt
> xpack.security.http.ssl.certificate_authorities: certs/ca.crt
> xpack.security.http.ssl.client_authentication: optional
> ```
> > ⚠️ Enabling SSL on HTTP layer will require all clients that connect to Elasticsearch to configure SSL connection for HTTP, this includes all the current configured parts of the stack (e.g Logstash, Kibana, Curator, etc) plus any library/binding that connects to Elasticsearch from your application code.

This decision was based on the face that enabling TLS for the HTTP Layer requires all clients connecting to Elasticsearch to be configured with the TLS Certificates which complicates using Elastdocker out of the box as you will need to configure TLS to every client/library you're using.

**Comment by sherifabdlnaby** [comment]
I thought about maintiang two branches with and without TLS enabled for HTTP, but I thought it would make it harder to maintain. What are your thoughts ? I don't want Elastdocker setup to force additional configuration to your web app that connects to Elasticsearch and hence was the decision to let it disabled by default.

**Comment by SelfhostedPro** [comment]
That definitely makes sense. I was a bit confused as it complains about TLS not HTTP security. Maybe just changing the wording in the documentation (possibly adding a screenshot) would resolve that issue for most people. I wouldn't worry about maintaining another branch just for that.

**Comment by sherifabdlnaby** [comment]
Before 7.8.0 it was not required to has TLS enabled for HTTP to use alerts.
