### ISSUE TITLE
kibana:elastdocker-7.9.2  STATUS unhealthy

### ISSUE THREAD

**Issue by allenshau** [sherifabdlnaby/elastdocker#26]
Looks the unhealthy caused "Kibana server is not ready yet".
How should I do?

**Comment by allenshau** [comment]
I found something about 7.9.3 downgrade 7.9.2 message although I use 7.9.2 in '.env':

{"type": "server", "timestamp": "2020-10-27T09:39:12,425Z", "level": "INFO", "component": "o.e.e.NodeEnvironment", "cluster.name": "elastdocker-cluster", "node.name": "elastdocker-node-0", "message": "heap size [1gb], compressed ordinary object pointers [true]" }
{"type": "server", "timestamp": "2020-10-27T09:39:12,520Z", "level": "ERROR", "component": "o.e.b.ElasticsearchUncaughtExceptionHandler", "cluster.name": "elastdocker-cluster", "node.name": "elastdocker-node-0", "message": "uncaught exception in thread [main]", 
"stacktrace": ["org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: **cannot downgrade a node from version [7.9.3] to version [7.9.2]",**

**Comment by sherifabdlnaby** [comment]
Are you sure you have not used `v7.9.3` at any point in time? because if so, Elasticsearch may make changes to its internal state that cannot be reverted, this state is persisted in the volume Docker creates for Elasticsearch and this volume isn't erased or replaced when you change the Elasticsearch containers.

Two possible ways to fix that:
1. If the data is not important, or not initialized yet, then you can erase the `elasticsearch-data` volume and restart the stack (This will erase everything you saved and every data you indexed).
2. Upgrade to `7.9.3` and use it with the current `elasticsearch-data` volume.

**Comment by sherifabdlnaby** [comment]
If you haven't used `v7.9.3` at any point, then we would need extra investigations as I can't replicate this at my setup.

**Comment by allenshau** [comment]
I tried to use 7.9.2 - not work.
I even tried to use 7.2.0 - not work either.
I finally use 7.9.3, not work either again. (no the error message cannot downgrade a node from version [7.9.3] to version [7.9.2] above.)
I am using Windows 10 20H2, Docker Desktop 2.3.0.5 with/without using WSL 2 - not work!
I'll try other environments to dig out further...
PS. Maybe you need to test 7.9.3 since the error message I found.

**Comment by sherifabdlnaby** [comment]
Looking at it

**Comment by allenshau** [comment]
Hi sherifabdlnaby ,

From your comments, I tried to totally clean my docker environment (2 cases: install another Win 10; prune the original one) and re-setup the ELK again.
And according to some error/warning messages, I expanded the host's RAM to 16GB and the docker resource to 6GB.
(Windows 10 20H2 with 16GB RAM, Docker Desktop 2.3.0.5, **not** using WSL 2)

Finally **it works** although with 2 containers unhealthy and 1 healthy. I guess some might be because of java **8** (!?).
Both 7.9.2 and 7.9.3 work fine.

    IMAGE                              STATUS                 NAMES
    elasticsearch:elastdocker-7.9.3    Up  (**unhealthy**)    elastic_elasticsearch_1
    kibana:elastdocker-7.9.3           Up  (**unhealthy**)    elastic_kibana_1
    logstash:elastdocker-7.9.3         Up  (**healthy**)      elastic_logstash_1

Many thanks for your information and your efforts of this project.

**Comment by sherifabdlnaby** [comment]
Hey @allenshau, I updated elastdocker to 7.9.3 today, and I didn't have a problem that led the stack to be in an unhealthy state.
I tried:
1- Upgrade an already existing `7.9.2` setup.
2- A clean install.

Also, by-reading (and according to SemVer) `7.9.2` -> `7.9.3` should not have any compatibility issues with any config when upgrading.

Can you share the logs from a starting elasticsearch or kibana container so we can know why it is unhealthy?

**Comment by allenshau** [comment]
Hi @sherifabdlnaby 

1. I re-cleaned my machine docker environment.

    rm all containers, images, volumes, networks
    prune container, volume, image, system, network

2. I re-donwloaded the new version from GitHub again (7.9.3)

3. make setup and make elk

4. Unfortunately, I still got 2 unhealthy containers, however, the https://localhost:5601/ works as the same.

```
docker ps
  IMAGE                             COMMAND                  STATUS            NAMES
  elasticsearch:elastdocker-7.9.3   "/tini -- /usr/local…"   Up  (unhealthy)   elastic_elasticsearch_1
  kibana:elastdocker-7.9.3          "/usr/local/bin/dumb…"   Up  (unhealthy)   elastic_kibana_1
  logstash:elastdocker-7.9.3        "/usr/local/bin/dock…"   Up  (healthy)     elastic_logstash_1
```
5. I attached the 6 logs of 3 containers by using the command below. Hope them help.

   `docker logs (id) --details 1>?1.txt 2>?2,txt`

6. I'll try clean it again by using uninstall the docker desktop or even prepare another machine to try again tomorrow.

[elastdocker-6logs.zip](https://github.com/sherifabdlnaby/elastdocker/files/5470403/elastdocker-6logs.zip)

**Comment by sherifabdlnaby** [comment]
I am not able to point out why it is unhealthy, the healthcheck script reports healthy for `green` and `yellow` status, if it is unhealthy that means Elasticsearch is `red` and subsequently, Kibana will be `red` too. You need to investigate why the Elasticsearch is not health at your setup, I've looked into the looks but it seems incomplete.

**Comment by allenshau** [comment]
I tried to inspect the containres by using **docker inspect (id)**.
I found some things like **"Output": "./docker-healthcheck: line 2: set: pipefail\r: invalid option name\n".**
I also attached the logs for your reference.

```
            "Health": {
                "Status": "unhealthy",
                "FailingStreak": 2289,
                "Log": [
                    {
                        "Start": "2020-11-02T03:05:39.73465791Z",
                        "End": "2020-11-02T03:05:39.832252734Z",
                        "ExitCode": 2,
                        "Output": "./docker-healthcheck: line 2: set: pipefail\r: invalid option name\n"
                        ... ...
```

[inspect-logs.zip](https://github.com/sherifabdlnaby/elastdocker/files/5472581/inspect-logs.zip)

**Comment by allenshau** [comment]
Hi @sherifabdlnaby,

From the message "... pipefail\r ...", then I guessed it should be from the DOS/UNIX EOL issue.
Looks these 2 scripts below were save as DOS text format.
```
.\elastdocker\elasticsearch\scripts\docker-healthcheck
.\elastdocker\kibana\scripts\docker-healthcheck
```
I converted them to UNIX text format and then stop/re-run these containers.
Now they all are healthy status.

Thanks a lot!

PS. You might need to update the source as well.

**Comment by sherifabdlnaby** [comment]
It is strange you had that because `.gitattributes` is configured to set EOL to LF for all *.sh files
https://github.com/sherifabdlnaby/elastdocker/blob/ed9f0d089ab9692fc25c562691bb21ffc69baf31/.gitattributes#L2

And I validated that by cloning the repository and check files and they were indeed LF.

**Comment by sherifabdlnaby** [comment]
Glad you found the issue and thank you for sharing your findings <3

**Comment by allenshau** [comment]
I found you closed this issue.
However, for Windows Docker Desktop users, you are supposed to correct `.gitattributes` since these 2 bash scripts are named without extension which make the `*.sh text eol=lf` no effect.
It would be some wording like: 
`scripts/* text eol=lf`
or
`docker-healthcheck text eol=lf`

Anyway, thanks for your efforts on this.
I learnt a lot.

**Comment by sherifabdlnaby** [comment]
You're right, sorry, I must have not been paying enough attention. I re-opened the issue until It is fixed, I suggest you make a PR to give yourself the contribution credits since you figured this out 👍  I'll wait some time for your PR if you want otherwise I'll fix it myself soon.

**Comment by allenshau** [comment]
I made a PR as your suggestion. :)
Hope I am doing right; you can see this is my first experience in GitHub.
Many thanks.

**Comment by devops-vivanetworks** [comment]
i get the error.. 
elastic_elasticsearch_1   /tini -- /usr/local/bin/do ...   Up (health: starting)   0.0.0.0:9200->9200/tcp, 0.0.0.0:9300->9300/tcp
elastic_kibana_1          /usr/local/bin/dumb-init - ...   Up (unhealthy)          0.0.0.0:5601->5601/tcp                        
elastic_logstash_1        /usr/local/bin/docker-entr ...   Up (healthy)            0.0.0.0:5044->5044/tcp, 0.0.0.0:9600->9600/tcp

and the elasticsearch logs :
elasticsearch_1  | {"type": "server", "timestamp": "2020-11-23T18:53:19,200Z", "level": "ERROR", "component": "o.e.b.ElasticsearchUncaughtExceptionHandler", "cluster.name": "elastdocker-cluster", "node.name": "elastdocker-node-0", "message": "uncaught exception in thread [main]",
