### ISSUE TITLE
Configure Fleet on Elastdocker

### ISSUE THREAD

**Issue by Volfskin** [sherifabdlnaby/elastdocker#29]
Hello, is there a possibility to configure this docker with Fleet and set: 
![image](https://user-images.githubusercontent.com/57900928/99409432-0a058100-28fa-11eb-91f2-1ee8d38ed155.png)
?
because after I'm setting the required information, the kibana server stops to respond. 

Thank u for your time spent on this q. :)

**Comment by sherifabdlnaby** [comment]
Yes, enabling `xpack.security.authc.api_key` requrires Elasticsearch to use SSL at the HTTP layer which is disabled by default in Elastdocker in favor of convenience as noted in the README.md.

You can enable SSL at HTTP by uncommenting the lines in elasticsearch.yml config, add the extra line in the screenshot and finally configure Kibana and Logstash and any other tool/code that connects to Elasticsearch to use SSL.

**Comment by Volfskin** [comment]
thank you so much for replying to me with so many tech-details, All clear now! have a great weak ahead.
