### ISSUE TITLE
Template Button Fails

### ISSUE THREAD

**Issue by notwedtm** [sherifabdlnaby/elastdocker#3]
Clicking the `Generate from Template` button leads to a 404.

**Comment by sherifabdlnaby** [comment]
You have to be logged in otherwise it shows 404 (weird behavior from Github, should prompt you to log-in instead)

**Comment by sherifabdlnaby** [comment]
https://github.com/sherifabdlnaby/elastdocker/generate
Please make sure you're logged in and check this link
