### ISSUE TITLE
Kibana docker-healthcheck script error

### ISSUE THREAD

**Issue by tvlc** [sherifabdlnaby/elastdocker#32]
Kibana docker healthcheck is failing:
./docker-healthcheck: line 5: python: command not found curl: (23) Failed writing body (0 != 16384)
Script is using python, which is not available.

**Comment by sherifabdlnaby** [comment]
Can confirm, python must have been removed in new images. It is not used heavily tho, I think `jq` can do its job here. 
I Will fix this when I have time, also PRs are welcomed ;)

**Comment by cahuete95** [comment]
Hi,

Same probleme noticed here.

**Comment by sherifabdlnaby** [comment]
Yes, I just haven't had the time to re-implement the healthcheck without python or `jq`, I removed the healthcheck from the latest version to avoid confusion, but I kept the issue open to eventually get to it.

**Comment by cahuete95** [comment]
> Yes, I just haven't had the time to re-implement the healthcheck without python or `jq`, I removed the healthcheck from the latest version to avoid confusion, but I kept the issue open to eventually get to it.

👍
