### ISSUE TITLE
Not working with custom username

### ISSUE THREAD

**Issue by okanakdogan** [sherifabdlnaby/elastdocker#34]
**Describe the bug**
stack not working with changing only username & password.
I changed username as "okan" and password "pass" for testing
If I use default username 'elastic', it's working.

**To Reproduce**
Clone the repo.
change username & password in .env file.
make setup
(virtual memory size set for linux)
make elk

**Expected behavior**
Run stack and see kibana login screen

Logs of elasticsearch:

{"type": "server", "timestamp": "2021-03-02T06:26:55,676Z", "level": "INFO", "component": "o.e.c.r.a.AllocationService", "cluster.name": "elastdocker-cluster", "node.name": "elastdocker-node-0", "message": "Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[.monitoring-es-7-2021.03.02][0]]]).", "cluster.uuid": "WIOpjgIqSZiqzZ3Utlz7aw", "node.id": "I2tuo0noSWyezMY7zIKDkQ"  }
elasticsearch_1  | {"type": "server", "timestamp": "2021-03-02T06:26:56,694Z", "level": "ERROR", "component": "o.e.x.s.a.e.NativeUsersStore", "cluster.name": "elastdocker-cluster", "node.name": "elastdocker-node-0", "message": "security index is unavailable. short circuiting retrieval of user [okan]", "cluster.uuid": "WIOpjgIqSZiqzZ3Utlz7aw", "node.id": "I2tuo0noSWyezMY7zIKDkQ"  }
elasticsearch_1  | {"type": "server", "timestamp": "2021-03-02T06:26:56,706Z", "level": "ERROR", "component": "o.e.x.s.a.e.NativeUsersStore", "cluster.name": "elastdocker-cluster", "node.name": "elastdocker-node-0", "message": "security index is unavailable. short circuiting retrieval of user [okan]", "cluster.uuid": "WIOpjgIqSZiqzZ3Utlz7aw", "node.id": "I2tuo0noSWyezMY7zIKDkQ"  }
elasticsearch_1  | {"type": "server", "timestamp": "2021-03-02T06:26:56,724Z", "level": "ERROR", "component": "o.e.x.s.a.e.NativeUsersStore", "cluster.name": "elastdocker-cluster", "node.name": "elastdocker-node-0", "message": "security index is unavailable. short circuiting retrieval of user [okan]", "cluster.uuid": "WIOpjgIqSZiqzZ3Utlz7aw", "node.id": "I2tuo0noSWyezMY7zIKDkQ"  }

Desktop:
 - OS: Linux 18.04
 - Browser chrome

**Comment by sherifabdlnaby** [comment]
1. Are you trying to change that master username after initializing the cluster?
2. Have you re-run the setup step `make setup`?

**Comment by okanakdogan** [comment]
Hey,
1. No, first thing I did is changing username&password in env. file. I didn't run any container before that.
2. Yes, I changed first env file then execute "make setup".

I read about "system built-in users" of elasticsearch. I guess this is a built-in username.
Can you change that username for fresh start?

**Comment by sherifabdlnaby** [comment]
@okanakdogan Oh, you're right, I don't remember why I had it this way, You can override the bootstrapping username yes. I'll update the repo and remove the option to avoid confusion. Sorry for the confusion too :')
