### ISSUE TITLE
Kibana not connect Elastalert

### ISSUE THREAD

**Issue by caotangdaiduong** [sherifabdlnaby/elastdocker#36]
FATAL  Error: Unknown configuration key(s): "elastalert-kibana-plugin.serverHost", "elastalert-kibana-plugin.serverPort". Check for spelling errors and ensure that expected plugins are installe

my config kibana/config/kibana.yml:
## ElastAlert Plugin
elastalert-kibana-plugin.serverHost: elastalert
elastalert-kibana-plugin.serverPort: 3030

ElastAlert contaner is running with "make tools"

Plz help me

**Comment by sherifabdlnaby** [comment]
You'll need to add to also uncomment the part in `Dockerfile` to install the plugin.
However, this ElastAlert is inactive and does not support latest Kibana versions, so uncomment it and enable it if you're using a supported version by the plugin.
