### ISSUE TITLE
Very slow when upgrade from 7.10 to 7.12.0

### ISSUE THREAD

**Issue by caotangdaiduong** [sherifabdlnaby/elastdocker#37]
I upgrade the JVM memory 4GB will it affect. My server has 12 core configuration, 16GB RAM

![image](https://user-images.githubusercontent.com/28684084/120910229-543c2d00-c6a7-11eb-8d6c-137a7892b3ad.png)

**Comment by sherifabdlnaby** [comment]
If the server is 16GB and you're using it exclusively for Elasticsearch, then you might wanna increase the JVM Heap to around 8~9GB otherwise you'll be underutilizing your resources.

Also, the disk type (Magnetic, SSD, etc ) affects Elasticsearch performance signficantly.
