### ISSUE TITLE
How to enable alert in elastdocker

### ISSUE THREAD

**Issue by haidt7** [sherifabdlnaby/elastdocker#41]
Ask a question...

Dear @sherifabdlnaby,
First, thanks you so much for your guide, it is very helpful for a newbie like me. But I have a question, how can i enable alert for Kibana, it says i must be enabled TLS:
![image](https://user-images.githubusercontent.com/10104900/133182422-45a60527-83fa-4952-8e68-39756ebd0d7d.png)
But in Repository Introduction => Main Features => SSL Enabled for Transport Layer and Kibana.
Can you help me to resolve this problem.

**Comment by sherifabdlnaby** [comment]
@haidt7 With the release of v2.0.0, TLS on Transport Layer is enabled by default.
  - Enables the usage of ELK Alerts
  - Enables the usage of ML Jobs
  - Enables the usage of SIEM features
