### ISSUE TITLE
Enable SSL on HTTP 

### ISSUE THREAD

**Issue by Dalador1** [sherifabdlnaby/elastdocker#42]
Hi! Thank you for this awesome project! 

Could you please, add some guide to enable SSL on HTTP? 

Should i use certs that generates for TLS and add path to them in kibana.yaml, logstash.yaml etc? 

Thank you! 
Best regards.

**Comment by sherifabdlnaby** [comment]
@Dalador1 With the release of v2.0.0, HTTPS is now enabled by default.
