### ISSUE TITLE
How to add logstash plugins?

### ISSUE THREAD

**Issue by bbatmandakh** [sherifabdlnaby/elastdocker#53]
Hi, 

In previous releases, there was Dockerfile for each app(elastic, logstash, kibana)...Looks like its missing.
Where I can install plugins? Is there new way to do it without Dockerfile?
like
 RUN logstash-plugin install logstash-filter-tld
RUN logstash-plugin install logstash-output-syslog

**Comment by sherifabdlnaby** [comment]
@bbatmandakh I am planning on reverting this change for Logstash, apologies for the inconvinence.

**Comment by ScottFred** [comment]
Until you have the time to reverting this change for Logstash, can you help me understand the best way to install a Logstash plugin?  Thanks!

**Comment by sherifabdlnaby** [comment]
@ScottFred  @bbatmandakh Functionality Restored in release v2.1.0
