### ISSUE TITLE
"Kibana server is not ready yet." after setting up containers

### ISSUE THREAD

**Issue by supmanyu** [sherifabdlnaby/elastdocker#69]
First of all, I'd like to thank you for creating such a comprehensive guide to getting started with ELK!

I have followed the tutorial to get the stack up and running and didn't face any issues there. However, if I try to access KIbana on https://localhost:5601/, I get "Kibana server is not ready yet." in the browser. One thing to note is that the elastic_elasticsearch_1 container is stuck in the "starting" state, which could be the cause of the issue, but I have waited for an hour and it has stayed in that state.

    Docker version 20.10.0, build 7287ab3
    docker-compose version 1.29.2, build 5becea4c
    
 `make ps` Output: 
 
                  Name                            Command                       State                               Ports                     
    ------------------------------------------------------------------------------------------------------------------------------------------
    elastic_elasticsearch-exporter_1   /bin/elasticsearch_exporte ...   Up                      0.0.0.0:9114->9114/tcp                        
    elastic_elasticsearch_1            /bin/tini -- /usr/local/bi ...   Up (health: starting)   0.0.0.0:9200->9200/tcp, 0.0.0.0:9300->9300/tcp
    elastic_filebeat-cluster-logs_1    /usr/bin/tini -- /usr/loca ...   Up                                                                    
    elastic_kibana_1                   /bin/tini -- /usr/local/bi ...   Up                      0.0.0.0:5601->5601/tcp                        
    elastic_logstash-exporter_1        /prometheus-logstash-expor ...   Up                      0.0.0.0:9304->9304/tcp                        
    elastic_logstash_1                 /usr/local/bin/docker-entr ...   Up (healthy)   0.0.0.0:5044->5044/tcp, 0.0.0.0:9600->9600/tcp
    elastic_rubban_1                   /opt/rubban/rubban               Up                                                                    

I'd be extremely grateful if you could point me in the right direction, thanks.

**Comment by jasonborchardt** [comment]
figured out my issue.  I needed to run this (ran it before, but needed to run it again after the reboot):
sudo sysctl -w vm.max_map_count=262144

**Comment by supmanyu** [comment]
thank you much! I also arrived at the same conclusion that there was a kernel panic happening due to a smaller max map count. closing this issue
