### ISSUE TITLE
docker-compose not found when running setup

### ISSUE THREAD

**Issue by AGSPhoenix** [sherifabdlnaby/elastdocker#7]
The README describes docker-compose as 'optional', but `make setup` immediately fails with an error if it's not on the PATH:
```
phoenix@dockerhost:~/elastdocker$ make setup
make[1]: Entering directory '/home/phoenix/elastdocker'
/bin/sh: 1: docker-compose: not found
Makefile:21: recipe for target 'certs' failed
make[1]: *** [certs] Error 127
make[1]: Leaving directory '/home/phoenix/elastdocker'
Makefile:24: recipe for target 'setup' failed
make: *** [setup] Error 2
```
It seems like every target in the makefile uses docker-compose, which isn't very optional.

**Comment by arguser** [comment]
Hello @AGSPhoenix 

It actually depends on `docker-compose`, you can optionally switch to that command or use `make`

> Makefile is a wrapper around Docker-Compose commands, use make help to know every command.
