### ISSUE TITLE
how to reset the password of a running stack

### ISSUE THREAD

**Issue by nikolinsko** [sherifabdlnaby/elastdocker#71]
Hi there, 

this might be a pretty dumb question but how do i change the password of an existing cluster?

i tried editing the .env file followed by make setup and

- docker stop/start elastic_elasticsearch_1 elastic_kibana_1 elastic_logstash_1
- docker-compose down -> docker-compose-up -d

My service is public facing and i messed the initial password up ;)

Thanks in advance

**Comment by sherifabdlnaby** [comment]
@nikolinsko You can use the [Change Password API](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-change-password.html). Or the [Utility Tools inside the container](https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-passwords.html) (by exec'ing inside). 

Another way would be to expose the password you want as an environment variable via `export ELASTIC_PASSWORD=<password>`, then run `make setup`, this should replace your existing `./secrets/keystore/elasticsearch.keystore` file that holds your `bootstrap.password`.

**Comment by nikolinsko** [comment]
thanks alot, i'll give it a try.

Closing this now :)
