### ISSUE TITLE
README error in Configuration section

### ISSUE THREAD

**Issue by enstit** [sherifabdlnaby/elastdocker#77]
**Bug description**

In the README file, under the Configuration section, you should change

* Logstash Pipeline in `main.conf` at `./elasticsearch/pipeline/main.conf`.

to

* Logstash Pipeline in `main.conf` at `./logstash/pipeline/main.conf`.

**Comment by sherifabdlnaby** [comment]
@enstit Thanks, I'll make sure to fix it on the next release, PRs are welcome too 😉
