### ISSUE TITLE
Adding elasticsearch Comrade to the stack

### ISSUE THREAD

**Issue by moshe** [sherifabdlnaby/elastdocker#8]
Hey @sherifabdlnaby 👋
I'm the maintainer of [elasticsearch-comrade an elasticsearch admin panel](https://github.com/moshe/elasticsearch-comrade) and I wonder if you will welcome a pr that adding Comrade to the stack

**Comment by sherifabdlnaby** [comment]
Hello @moshe, first, I apologize for the late reply as I was away the past month. I didn't know about elasticsearch comrade, it looks very helpful, I'll give it a try, and of course, a PR is welcomed anytime 🙏🏻
