### ISSUE TITLE
Enable config option to run Kibana over http

### ISSUE THREAD

**Issue by hicnar** [sherifabdlnaby/elastdocker#95]
It looks like currently this project runs Kibana only with self signed ssl certificate that must be generated before the containers it creates can be started for the first time. 
I have a wildcard ssl certificate signed by a trusted CA and would like to be able to run Kibana behind a reversed proxy that would redirect requests to the backend (in this case the backend would be Kibana running over http) and expose Kibana to the outside world via https with my SSL certificate. 
To enable that  I would like to have a config option to run Kibana over http and redirect to it by configuring my DNS and reversed proxy without having to clone and modify the elastdocker (ex registering my cert with Kibana docker image so that it uses it instead of the self signed generated one) and more importantly having to store/update the certificate in multiple locations.

**Comment by sherifabdlnaby** [comment]
Hello @hicnar 
The repo is designed to be a template with sane defaults that work for the most common case, so it's expected to modify to suit your needs. For your case, I'd configure the Proxy to skip SSL verification.
